beautyprof/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.ProfileListView.as_view(), name='home'),
    path('add/', views.add_profile, name='add_profile'),
    path('view/', views.view_my_profile, name='view_my_profile'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('delete/', views.delete_profile, name='delete_profile'),
    path('<slug:slug>/', views.ProfileDetail.as_view(), name='profile_detail'),
]

salon/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beautyprof.urls'), name='beautyprof_urls'),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
]

beautypost/models.py
from django.db import models

# Create your models here.

beautyprof/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
# Import slugify to generate slugs from strings
from django.utils.text import slugify


class Profile(models.Model):
    name = models.CharField(max_length=200, blank=True)
    profession = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="add about your work and contact",
                           max_length=300)
    slug = models.SlugField(blank=True, unique=True)
    email = models.EmailField(max_length=200, blank=True)
    county = models.CharField(max_length=200, blank=True)
    avatar = CloudinaryField('image', default='placeholder')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user)
        super(Profile, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.username}"


class Meta:
    ordering = ['created_on']

    def __str__(self):
        return str(self.username)


class Review(models.Model):

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE,
                                related_name="reviews")
    first_name = models.CharField(max_length=80)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Review {self.body} by {self.first_name}"

beautyprof/forms.py
from django import forms
from .models import Profile, Review


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'profession', 'email', 'county', 'avatar', 'bio']
        prepopulated_fields = {'slug': 'user'}


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('body',)

beautypost/views.py
from django.shortcuts import render

# Create your views here.

beautyprof/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic, View
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView
from django.contrib import messages
from .models import Profile, Review
from .forms import ProfileForm, ReviewForm
from django.contrib.messages.views import SuccessMessageMixin


class ProfileListView(generic.ListView):
    model = Profile
    queryset = Profile.objects.order_by('created')
    template_name = "index.html"
    paginate_by = 6


"""Detailed view of individual Profile"""


class ProfileDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Profile.objects.order_by('updated')
        profile = get_object_or_404(queryset, slug=slug)
        reviews = profile.reviews.order_by("-created_on")
        review_form = ReviewForm()

        return render(
            request,
            "profile_detail.html",
            {
                "profile": profile,
                "reviews": reviews,
                "reviewed": False,
                "review_form": review_form,
                })

    def post(self, request, slug, *args, **kwargs):
        queryset = Profile.objects.all()
        profile = get_object_or_404(queryset, slug=slug)
        reviews = profile.reviews.order_by("-created_on")
        review_form = ReviewForm()
        review_form = ReviewForm(data=request.POST)

        if review_form.is_valid():
            review_form.instance.email = request.user.email
            review_form.instance.first_name = request.user.username
            review = review_form.save(commit=False)
            review.profile = profile
            review.save()
            review_form = ReviewForm()
            messages.success(request, 'Review added successfully.')
        else:
            review_form = ReviewForm()

        return render(
            request,
            "profile_detail.html",
            {
                "profile": profile,
                "reviews": reviews,
                "reviewed": True,
                "review_form": review_form,
                })


@login_required
def view_my_profile(request):
    profile = get_object_or_404(Profile, user=request.user)
    reviews = profile.reviews.order_by("-created_on")
    return render(request, 'view_profile.html', {'profile': profile,
                                                 'reviews': reviews, })


@login_required
def add_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user = request.user
            profile = form.save(commit=False)
            profile.save()
            messages.success(request, 'Profile created successfully.')
            return redirect('view_my_profile')
    else:
        form = ProfileForm()
    context = {
        'form': form,
         }

    return render(request, 'add_profile.html', context)


@login_required
def edit_profile(request):
    profile = get_object_or_404(Profile, user=request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect('view_my_profile')
    else:
        form = ProfileForm(instance=profile)

    context = {
        'form': form,
        'user': profile,
            }
    return render(request, 'edit_profile.html', context)


@login_required
def delete_profile(request):
    profile = get_object_or_404(Profile, user=request.user)
    if request.method == 'POST':
        profile.delete()
        messages.success(request, 'Profile deleted successfully.')
        return redirect('home')
    return render(request, 'delete_profile.html', {'profile': profile})


"""custom error handling page 404 and 500"""


def handler404(request, exception):
    return render(request, "errors/404.html", status=404)


def handler500(request):
    return render(request, "errors/500.html", status=500)

templates/add_profile.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <h3>Create Profile</h3>
            <p>Please create a profile with detailed bio about your work</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2 border border-dark border-2 rounded-4 justify-content-center">
            <form enctype="multipart/form-data" method="POST" >
                {% csrf_token %}
                {{ form.media }}
                {{ form.name| as_crispy_field }}
                {{ form.profession | as_crispy_field }}
                {{ form.email| as_crispy_field }}
                {{ form.county | as_crispy_field }}
                {{ form.avatar | as_crispy_field }}
                {{ form.bio | as_crispy_field }}
                </select>
                <br>
                <button type="submit" class="btn btn-secondary"> Create</button>
                <a href="{% url 'home' %}" role="button" class="btn btn-secondary">Go back</a>
            </form>
        </div>
    </div>
    <br>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- links from blog before i think tutorial -->

  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
  </script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <title>Freelance Beauticians</title>
</head>

<body class="d-flex flex-column h-100 main-bg">

  <!-- Navigation -->

  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img class="d-inline-block align-top img-fluid"
          src="https://res.cloudinary.com/mycodestudies/image/upload/v1682078824/bbPP4_logo-transformed_mutiga.png"
          alt="logo image">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          {% if request.user.is_authenticated %}

          {% if request.user.is_staff %}

          <a class="nav-link" href="https://pp4-beautysalon.herokuapp.com/admin/" target="_blank">Admin Panel</a>
          <!-- only show when user create the profile -->
          {% endif %}
          {% if request.user.profile %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'view_my_profile' %}"> My Profile</a>
          </li>
          {% else %}
          <li class="nav-item"></li>
          <a class="nav-link" href="{% url 'add_profile' %}">Create Profile</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Sign Out</a>
          </li>
          <!-- logged in as user name on the left side -->
          <li class="nav-item">
            <p class="nav-link text-left">{{request.user}}</p>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Sign In</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
          {{ message | safe }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <main class="flex-shrink-0 main-bg">

    {% block content %}
    <!-- content goes here -->
    {% endblock content %}
  </main>

  <!-- Footer -->
  <footer class="footer mt-auto py-3 dark-bg">
    <p class="m-0 text-center text-white">Follow us:
      <a href="https://www.facebook.com/" target="blank"><i class="fab fa-facebook-square ms-3"></i></a>
      <a href="https://www.instagram.com/" target="blank"><i class="fab fa-instagram-square ms-3"></i></a>
    </p>

  </footer>

  <!-- Javascript Alert Messages taken from Code Institute: I think therefore I Blog -->


  <script>
    setTimeout(function () {
      let messages = document.getElementById("msg");
      let alert = new bootstrap.Alert(messages);
      alert.close();
    }, 3000);
  </script>

</body>

</html>

templates/delete_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="masthead">
  <div class="container">
    <div class="row g-0">
      <div class="col-md-6 masthead-text">
        <h3>Delete Profile</h3>
        <p>Are you sure you want to delete your profile?</p>
      </div>
    </div>
    <form method="post">
      {% csrf_token %}
      <button type="submit">Delete</button>
    </form>
  </div>
</div>

{% endblock %}

templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<header>
  <div class="container">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
          <h3>Edit Profile</h3>
        </div>
    </div>
    <div class="row">
      <div class="col-md-8 mt-3 offset-md-2 border border-dark border-2 rounded-4 justify-content-center">
          <br>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.media }}
            <button type="submit">Save</button>
          </form>
      
      </div>
    </div>
  </div>
</header>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

  <!-- site heading -->
<header class="masthead masthead-text">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div>
          <h2><span>Freelance</span>
            <span>Stylists</span>
            <span> and </span> 
            <span>Makeup</span>
            <span>Artists</span></h2>
        </div>
      </div>
    </div>
  </div>
</header>
<br>
<div class="container-fluid">
    <div class="row">

        <!-- Profile Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for profile in profile_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in profile.avatar.url %}
                                <img class="card-img-top rounded-circle mb-3" 
                                    src="https://res.cloudinary.com/mycodestudies/image/upload/v1682080266/makeup-transformed_dkltfn.jpg" alt="Avatar" >
                                {% else %}
                                <img class="card-img-top rounded-circle mb-3" src=" {{ profile.avatar.url }}" alt="profile image of the user">
                                {% endif %}
                                <div class="image-flash">
                                    <a href="{% url 'profile_detail' profile.slug %}" class="post-link"></a>
                                    <h5 class="mb-2"><strong>{{ profile.name }}</strong></h5>
                                </div>
                            </div>
                            <a href="{% url 'profile_detail' profile.slug %}" class="post-link">
                                <p class="text-muted h5">{{ profile.profession }} </p>

                            </a>
                            <hr>
                            <p class="card-text text-muted h6">{{ profile.created_on}}</p>


                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    <!-- pagination -->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}

templates/profile_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<header class="masthead masthead-text">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div>
                    <h2>Profile of {{profile.name}}</h2>
                    <br>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Profile title and profession -->
                <h1>{{profile.name}}</h1>
                <p>{{profile.profession}}</p>
                <p>{{profile.email}} </p>
                <p>{{profile.county}} </p>
                <p>{{profile.created_on}} </p>

            </div>
            <div class="d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in profile.avatar.url %}
                <img src="https://res.cloudinary.com/mycodestudies/image/upload/v1682080266/makeup-transformed_dkltfn.jpg"
                    style="width:80%;" alt="profile image">
                {% else %}
                <img src="{{ profile.avatar.url }}" style="width:80%;" alt="user has uploaded a custom image">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row white_div_margin">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- user bio -->
                <p class="card-text ">
                    {{profile.bio | safe}}
                </p>
            </div>
            <div class="row">
                <div class="col-1">
                    {% with reviews.count as total_reviews %}
                    <strong class="text-secondary"><i class="far fa-comments"></i>
                        <!-- Our total_comments variable goes before the closing strong tag -->
                        {{ total_reviews}}</strong>
                    {% endwith %}
                </div>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row white_div_margin">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h6>Reviews:</h6>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags to iterate through each review in reviews -->
                {% for review in reviews %}
                <div style="padding: 8px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ review.first_name }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ review.created_on }}
                        </span> wrote:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ review.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        {% if user.is_authenticated %}
        {% if request.user != profile.user %}
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <h3>Write a Review:</h3>
                <p>Posting as: {{ request.user }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ review_form | crispy }}
                    {% csrf_token %}
                    <br>
                    <button type="submit" class="btn btn-secondary">Submit</button>
                </form>
            </div>
        </div>
        {% endif %}
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/profilehtml/profile_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ profile.name }}</h1>
<p>Email: {{ profile.email }}</p>
<p>Bio: {{ profile.bio }}</p>
{% endblock %}

templates/profilehtml/profile_form.html
<!-- {% extends 'base.html' %}

{% block content %}
<h1>Create Profile</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
{% endblock %} -->

templates/view_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<header class="masthead masthead-text">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto ">
                <div>
                    <h2>My Profile</h2>
                    <br>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <p><strong>First Name: </strong> {{ profile.name }}</p>
                <p><strong>Profession: </strong> {{ profile.profession }}</p>
                <p><strong>Email: </strong> {{ profile.email }}</p>
                <p><strong>Bio: </strong> {{ profile.bio }}</p>
                <p><strong>Profile image: </strong> </p>
                <br>
            </div>

            <div class="d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in profile.avatar.url %}
                <img src="https://res.cloudinary.com/mycodestudies/image/upload/v1682080266/makeup-transformed_dkltfn.jpg"
                    style="width:80%; margin-top: 2em;" alt="profile image">
                {% else %}
                <img src="{{ profile.avatar.url }}" style="width:80%; margin-top: 2em;" alt="user has uploaded a custom image">
                {% endif %}
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col">
                <hr>
            </div>
        </div>
        <div class="row white_div_margin">
            <div class="col-md-8 card mb-4  mt-3 ">
                <h6>Reviews:</h6>
                <div class="card-body">
                    <!-- We want a for loop inside the empty control tags to iterate through each review in-reviews -->
                    {% for review in reviews %}
                    <div style="padding: 10px;">
                        <p class="font-weight-bold">
                            <!-- The commenter's name goes here.-->
                            {{ review.first_name }}
                            <span class=" text-muted font-weight-normal">
                                <!-- The comment's created date goes here -->
                                {{ review.created_on }}
                            </span> wrote:
                        </p>
                        <!-- The body of the comment goes before the | -->
                        {{ review.body | linebreaks }}
                    </div>
                    <!-- Our for loop ends here -->
                    {% endfor %}
                </div>
            </div>
        </div>
        <br>
        <div>
            <a href="{% url 'edit_profile' %}">Edit Profile</a>
            <br>
            <a href="{% url 'delete_profile' %}">Delete Profile</a>
        </div>
    </div>
</div>

{% endblock %}